name: birdnet_pi_app
description: "BirdNET-Pi - App Flutter per il monitoraggio degli uccelli"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.1
  go_router: ^17.1.0
  dio: ^5.8.0+1
  fl_chart: ^1.1.1
  just_audio: ^0.10.5
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  shimmer: ^3.0.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  pointer_interceptor: ^0.10.1+2
  universal_html: ^2.3.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/logo.png
    - assets/google_fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/google_fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/google_fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/google_fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/google_fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/google_fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/google_fonts/Inter-Black.ttf
          weight: 900
    - family: RobotoMono
      fonts:
        - asset: assets/google_fonts/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/RobotoMono-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/google_fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Roboto-Bold.ttf
          weight: 700
    - family: NotoSansSymbols
      fonts:
        - asset: assets/google_fonts/NotoSansSymbols-Regular.ttf
          weight: 400
